name: Documentation
description: Report an issue related to the LangChain documentation.
title: "DOC: <Please write a comprehensive title after the 'DOC: ' prefix>"
labels: [03 - Documentation]

body:
- type: markdown
  attributes:
    value: >
      Thank you for taking the for a feature request.
      
      If you have usage questions or need help solving some problem, 
      please use [GitHub Discussions](https://github.com/langchain-ai/langchain/discussions).
      
      [LangChain documentation with the integrated search](https://python.langchain.com/docs/get_started/introduction),
      [API Reference](https://api.python.langchain.com/en/stable/),
      [GitHub search](https://github.com/langchain-ai/langchain),
      [LangChain Github Discussions](https://github.com/langchain-ai/langchain/discussions),
      [LangChain Github Issues](https://github.com/langchain-ai/langchain/issues?q=is%3Aissue),
      [LangChain ChatBot](https://chat.langchain.com/)
- type: checkboxes
  id: checks
  attributes:
    label: Checklist
    description: Please confirm and check all the following options.
    options:
      - label: I added a very descriptive title to this issue.
        required: true
      - label: I included a link to the documentation page I am referring to (if applicable).
        required: true
- type: textarea
  attributes: 
    label: "Feature request:"
    description: >
      Description of your feature request.
      Please make sure to leave a reference to documents/code you're
      referring to. Feel free to include names of classes, functions, methods
      or concepts you'd like to utilize/enhance.
